### ISSUE TITLE
Bugtton library logic error

### ISSUE THREAD

**Issue by mertcan-basut** [mertcan-basut/chess-clock#1]
## Problem Definition
Bugtton library's functions `bool fell(button_i)` and `bool rose(button_i)` returns logically inverted results due to an unknown error. Other functions haven't been tested yet.

Possible error sources:
- [chess-clock/chess_clock.ino](https://github.com/mertcan-basut/chess-clock/blob/7d8d418bb10172c4cc05cdac5ecedde128cf5e8a/chess_clock.ino)
- [chess-clock/src/Bugtton](https://github.com/mertcan-basut/chess-clock/tree/7d8d418bb10172c4cc05cdac5ecedde128cf5e8a/src/Bugtton)
- Circuit design

## TO-DO List
- [ ] Test the issue for other functions of the library
- [ ] Check if the error caused by the library's source code or circuit connections
- [ ] Resolve the issue

## Solution
Not solved yet.
